### ISSUE TITLE
replication deadlocks after Unreachable error from the Network

### ISSUE THREAD

**Issue by pepinns** [datafuselabs/openraft#833] opened 2023-05-11 17:35 UTC
**Describe the bug**
When you modify the example network implementation to treat 'Connection Refused' or similar errors as Unreachable, the ReplicationCore main() loop seems to block forever in drain_events

**To Reproduce**
1. Update the rocksdb example to use Unreachable in the event one of the nodes is unavailable.
2. modify the script that runs the example to stop the leader node, and bring it back online a bit later after a new leader is chosen.

**Expected behavior**
The downed leader will come back as a Follower

**Actual behavior**
The downed leader comes back initially as a Follower, but can receive no updates, and ultimately eventually becomes Candidate, and the split never resolves itself.   The 2 nodes from the cluster that stayed up keep communicating with each other, and the one that was down appears to be all alone.

**Env (please complete the following information):**
- OS: linux
- CPU: AMD EPYC
- Rust-toolchain: nightly-2023-05-04
- Openraft version 0.8.4 ( current main branch )

**Additional context**
The fix seems to be to change the end of main() to run *either*   backoff_drain_events or drain_events, but not 1 after the other.
```            
            if let Some(b) = &mut self.backoff {
                let duration = b.next().unwrap_or_else(|| {
                    tracing::warn!("backoff exhausted, using default");
                    Duration::from_millis(500)
                });

                self.backoff_drain_events(Instant::now() + duration).await?;
            } else {
                self.drain_events().await?;
            }

```

With this change, the backoff_drain_events happens every 500ms, until the node comes back.  Then it seems to rejoin the cluster and get heartbeats again.

Without this change, this code seems to hang forever 
```
  pub async fn drain_events(&mut self) -> Result<(), ReplicationClosed> {
        tracing::debug!("drain_events");

        let event = self.rx_repl.recv().await.ok_or(ReplicationClosed {})?;   <-- never returns

```

The change doesn't make any existing tests fail.

**Comment by drmingdrmer** [comment] 2023-05-12 01:42
Thank you for reporting this issue in detail and proposing a fix.

What's the version of openraft were you using? I'll check if the issue has been resolved in the main branch.

With the latest main branch, if there is a pending action, `drain_events` will return immediately:
https://github.com/datafuselabs/openraft/blob/5da9594d3658e5d1637d8e0a896f6724fdc918f9/openraft/src/replication/mod.rs#L508-L518

And `RaftCore` will periodically send an heartbeat event to `ReplicationCore` to wake up it thus `self.rx_repl.recv()` should not block for ever.

**Comment by drmingdrmer** [comment] 2023-05-12 03:27
I was unable to reproduce the issue with a test case. Could you assist me in confirming that the steps in this test align with the steps in your situation:

- #834

And with `export RUST_LOG=debug`, the testing script will output debug level logs, which may help on tracing this issue.

**Comment by pepinns** [comment] 2023-05-12 14:22
I was on a previous version of main.   I'll try again with this updated code and see if this resolves it.  My version definitely doesn't have that if statement.

**Comment by pepinns** [comment] 2023-05-12 17:18
The updated main branch resolves this issue.

**Closed** 2023-05-12 17:17 UTC
Labels: replication

**Comment by drmingdrmer** [comment] 2023-05-13 06:01
> I was on a previous version of main. I'll try again with this updated code and see if this resolves it. My version definitely doesn't have that if statement.

Right. I found this bug and fixed it after pushing the `backoff` to github. :(
